name: Build and Deploy to Firebase

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Create configs file
        uses: finnp/create-file-action@1.0.0
        env:
          FILE_NAME: "src/configs.js"
          FILE_DATA: "const firebaseConfig = {apiKey: 'AIzaSyCAmpmMEFT9nbMaTjI4YDqAa1H1zufc9r0',authDomain: 'deposit-ce46e.firebaseapp.com',databaseURL: 'https://deposit-ce46e.firebaseio.com',storageBucket: 'deposit-ce46e.appspot.com',messagingSenderId: '713372742623'};export {firebaseConfig};"
      - name: Install dependencies
        run: npm install
      - name: Build for production
        run: npm run build
      - name: Archive production artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build
  deploy:
    name: Deploy to Firebase Hosting
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}